return a processed tx by chain when generating transactions
Ludex-Labs/ludex-sdk-js pull request #41
Opened 2023-12-19 05:26 UTC by allentsangdev

pre process the base64 transaction string returned from the REST API and return a ready to use transaction object. 

Considering the potential impact on our existing SDK and API consumers, implementing this change at the REST API level would disrupt their current code. Therefore, implementing this change at the SDK level. Existing SDK users can then install our latest SDK and update their code base accordingly.

clickup ticket: https://app.clickup.com/t/8686cc05p

2024-02-14 18:11 UTC, mccjul requested changes

2024-02-14 18:11 UTC, mccjul commented on package.json
> +    "@solana/web3.js": "^1.87.6",
remove web3 lib

2024-02-14 18:11 UTC, mccjul commented on src/utilities.ts
> +      return Transaction.from(Buffer.from(txn, "base64"));
just send out buffer as they can create a transaction from that and keeps our sdk lightweight

2024-02-14 19:06 UTC, mccjul commented on src/utilities.ts
> +/**
Would be great to have an example in the jsdoc of how I could use the solana transaction vs the avalanche transaction

2024-02-14 19:08 UTC, Ibby-debug approved these changes

2024-02-20 23:07 UTC, mccjul approved these changes

2024-02-20 23:08 UTC, merged